<?php

/**
 * @file
 * Contains module code.
 */

require 'includes/addtocalendar.form.inc';
require 'includes/addtocalendar.build.inc';

/**
 * Implements hook_field_formatter_third_party_settings_form().
 */
function addtocalendar_field_formatter_third_party_settings_form($plugin, $field_definition, $view_mode, $form, $form_state) {
  $element = [];
  if (in_array('datetime', $plugin->getPluginDefinition()['field_types'])) {
    $settings = $plugin->getThirdPartySettings('addtocalendar');
    $element = _addtocalendar_build_form($settings, $field_definition);
  }
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary_alter().
 */
function addtocalendar_field_formatter_settings_summary_alter(&$summary, $context) {
  if (in_array('datetime', $context['formatter']->getPluginDefinition()['field_types'])) {
    if ($context['formatter']->getThirdPartySetting('addtocalendar', 'addtocalendar_show')) {
      $summary[] = t('Add to calendar enabled');
    }
  }
}

/**
 * Implements hook_preprocess_field().
 */
function addtocalendar_preprocess_field(&$variables) {
  if ($variables['field_type'] == 'datetime') {
    _addtocalendar_preprocess_field($variables);
  }
}
