<?php

/**
 * @file
 */

require 'includes/addtocalendar.form.inc';

/**
 * Implements hook_help().
 */
function addtocalender_help($path, $arg) {
  switch ($path) {

    case 'admin/help#addtocalender':
      $output = file_get_contents(drupal_get_path('module', 'addtocalendar') . '/README.md');
      return $output;
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function addtocalendar_field_formatter_info() {
  return array(
    /*
     *'text_default' => array(
     *  'label' => t('Default'),
     *  'field types' => array('text', 'text_long', 'text_with_summary'),
     *),
     */
    'add_to_calender' => array(
      'label' => t('Add to calendar'),
      'field types' => array('date', 'datestamp', 'datetime'),
      'settings' => array(
        'addtocalendar_show' => '',
        'addtocalendar_settings' => '',
      ),
    ),
  );
}

/**
 *
 */
function addtocalendar_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  if ($field['type'] == 'datetime') {
    $element = _addtocalendar_build_form($settings, $field);
  }
  return $element;

}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function addtocalendar_field_formatter_settings_summary($field, $instance, $view_mode) {

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = '';

  if ($field['type'] == 'datetime') {
    if (array_key_exists('addtocalendar_show', $settings)) {
      $summary = t('Add to calendar: @value', array('@value' => ($settings['addtocalendar_show'] ? 'yes' : 'no')));
    }
  }
  return $summary;

}
